### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by denisbetsi** [megastef/node-crate#14]
I have a loop that looks up orders and creates an array of promises of "select" statements with limi 1. This issue appears randomly, when there's few hundred simultaneous select statements that get launched I end up seeing this error without any description

`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)`

It fails the whole app rather then 1 select statement. I've noticed if I limit # of lookups to much smaller # the error goes away.

**Comment by denisbetsi** [comment]
I enabled trace to see where it's failing

`
Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:687:35)
    at tickOnSocket (_http_client.js:560:10)
    at onSocketNT (_http_client.js:580:5)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
---------------------------------------------
    at ClientRequest.onSocket (_http_client.js:572:11)
    at _http_agent.js:164:11
    at oncreate (_http_agent.js:235:5)
    at Agent.createSocket (_http_agent.js:197:5)
    at Agent.addRequest (_http_agent.js:157:10)
    at new ClientRequest (_http_client.js:160:16)
    at Object.exports.request (http.js:31:10)
    at Contructor.Send [as queryPost] (/SMS/node_modules/crate-connect/src/connect.query.js:21:21)
    at Select.Run (/SMS/node_modules/cratejs/src/select.js:58:22)
`

**Comment by denisbetsi** [comment]
Just realized this is not the right library to post this issue with :|
